# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_auto_20170110_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('applications', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5e94\u7528')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='host',
            name='describe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='describe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u540d\u79f0'),
        ),
    ]
