# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20170220_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_role',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='\u89d2\u8272'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolemanage',
            name='describe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0'),
        ),
    ]
