# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20170220_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_role',
            field=models.CharField(default='default_role', max_length=100, verbose_name='\u89d2\u8272'),
        ),
    ]
