# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20170220_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='host_role',
            new_name='host_roles',
        ),
    ]
