# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20170220_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ssh_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SSH key'),
        ),
        migrations.AlterField(
            model_name='host',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='password'),
        ),
    ]
