# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20170301_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_group',
        ),
    ]
