# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_remove_host_host_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='ssh_key',
        ),
        migrations.AlterField(
            model_name='host',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='password'),
            preserve_default=False,
        ),
    ]
