# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20170301_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemanage',
            name='applications',
        ),
        migrations.AlterField(
            model_name='rolemanage',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='\u540d\u79f0'),
        ),
    ]
