# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20170301_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemanage',
            name='play_book',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5e94\u7528'),
        ),
    ]
