# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20170301_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemanage',
            name='timeout',
            field=models.IntegerField(default=180),
            preserve_default=False,
        ),
    ]
