# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_rolemanage_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemanage',
            name='timeout',
            field=models.IntegerField(default=180),
        ),
    ]
