# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0014_auto_20170305_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('describe', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rolemanage',
            name='dynamic_vars',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u52a8\u6001\u53d8\u91cf'),
        ),
        migrations.AlterField(
            model_name='rolemanage',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='rolemanage',
            name='playbook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Playbook'),
        ),
        migrations.AlterField(
            model_name='rolemanage',
            name='timeout',
            field=models.IntegerField(default=180, verbose_name='\u8d85\u65f6\u65f6\u957f(s)'),
        ),
    ]
