# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20170308_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DynamicVariable',
            new_name='DynamicVar',
        ),
    ]
