# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0016_auto_20170308_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rolemanage',
            name='timeout',
            field=models.IntegerField(default=120, verbose_name='\u8d85\u65f6\u65f6\u957f(s)'),
        ),
        migrations.AddField(
            model_name='host_role',
            name='role_manage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.RoleManage'),
        ),
        migrations.AddField(
            model_name='host_role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
