# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20170308_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_roles',
        ),
    ]
