# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0018_remove_host_host_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic_Variable_Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dynamic_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.DynamicVar')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Host')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role_Dynamic_Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dynamic_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.DynamicVar')),
                ('role_manage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.RoleManage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
