# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_rolemanage_step_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemanage',
            name='playbook_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Playbook\u540d\u79f0'),
        ),
    ]
