# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_rolemanage_playbook_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemanage',
            name='num',
            field=models.IntegerField(default=0, verbose_name='\u5e8f\u53f7'),
            preserve_default=False,
        ),
    ]
