# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_auto_20170315_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemanage',
            name='timeout',
            field=models.IntegerField(default=180, verbose_name='\u8d85\u65f6\u65f6\u957f(s)'),
        ),
    ]
