# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_auto_20170327_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemanage',
            name='step_count',
        ),
        migrations.AlterField(
            model_name='dynamicvar',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='\u540d\u79f0'),
        ),
    ]
