# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_parameter_task_tasklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='group',
        ),
        migrations.AddField(
            model_name='parameter',
            name='pgroup',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='\u7ec4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(max_length=60, verbose_name='\u503c'),
        ),
    ]
