# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20170223_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='ansible_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
