# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_tasklog_ansible_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='ansible_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
