# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20170302_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='role_names',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
