# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_remove_host_host_roles'),
        ('workflow', '0012_auto_20170309_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='role_name',
        ),
        migrations.AddField(
            model_name='parameter',
            name='is_dynamic_var',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parameter',
            name='role_manage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.RoleManage'),
            preserve_default=False,
        ),
    ]
