# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_task_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_result',
            name='task_log',
        ),
        migrations.RemoveField(
            model_name='task_result',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task_Result',
        ),
    ]
