# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20170313_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_result',
            name='ansible_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u4efb\u52a1\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='task_result',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u8fd4\u56de\u7ed3\u679c'),
        ),
    ]
