# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20170313_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='num',
            field=models.IntegerField(default=1, verbose_name='\u5e8f\u53f7'),
            preserve_default=False,
        ),
    ]
