# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_tasklog_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u540d\u79f0'),
        ),
    ]
