# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_auto_20170315_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='step_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
