# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_auto_20170406_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='step_count',
            field=models.IntegerField(default=0),
        ),
    ]
